### PR TITLE
Formatted code nicely

### PR DESCRIPTION
**Pull request by TLGINO**

### CODE REVIEW

**Comment by AHsofty** [comment]
Are you a bot?

**Comment by TLGINO** [comment]
Maybe

Eren ***@***.***> schrieb am Di., 28. Juni 2022, 23:08:

**Comment by TLGINO** [comment]
I'm disappointed in you, both for closing my pull request, but especially for the Amogus in SplashScreen.java
Shame

**Comment by ipsvn** [comment]
Amogus increases code quality

**Comment by AHsofty** [comment]
I'm sorry man, but your bot messed up a lot of the comments.

Super sussy wussy not cool.

**Comment by TLGINO** [comment]
I will be back tomorrow to format comments correctly, see you then

**Comment by ipsvn** [comment]
These machine learning algorithms have really got advanced eh?

**Comment by AHsofty** [comment]
Alrighty see you then.

**Pull request closed without merging**
